[server]
headless = true
runOnSave = true
[browser]
gatherUsageStats = false
[theme]
base = "light"
primaryColor = "#0B5B8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#111111"
[client]
showSidebarNavigation = true
[global]
dataFrameSerialization = "legacy"
