[theme]
base = "light"
primaryColor = "#0073CF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1F2937"
font = "sans serif"

[browser]
serverAddress = "localhost"
serverPort = 8501
